In [1]:
print("hello world")

hello world


In [2]:
#how to create numpy array
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2d=np.array([[1,2,3],[4,5,6]])

In [7]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr5=np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr5=np.arange(10,15)
arr5

array([10, 11, 12, 13, 14])

In [12]:
arr5=np.arange(10,15,2)
arr5

array([10, 12, 14])

In [13]:
arr6=arr5.copy()
arr6

array([10, 12, 14])

In [14]:
arr7=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
arr7

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [15]:
arr7.shape

(2, 2, 3)

In [16]:
arr7.ndim

3

In [17]:
arr7.size

12

In [18]:
arr7.itemsize

4

In [19]:
arr2d.itemsize

4

In [20]:
arr7.dtype

dtype('int32')

In [21]:
arr7.astype('float')

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[7., 8., 9.],
        [1., 2., 3.]]])

In [22]:
import sys
lista=range(100)
print(sys.getsizeof(87)*len(lista))

2800


In [23]:
arr10=np.arange(100)
print(arr10.itemsize*arr10.size)

400


In [24]:
arr11=np.array([1,2,3,4])
arr11

array([1, 2, 3, 4])

In [25]:
arr12=np.arange(20).reshape(5,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
arr12[2]

array([ 8,  9, 10, 11])

In [27]:
arr12[(2,1)]

9

In [28]:
arr12[:,1]

array([ 1,  5,  9, 13, 17])

In [29]:
arr12[:,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [30]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [31]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [33]:
arr12[3:5,0:2]

array([[12, 13],
       [16, 17]])

In [34]:
 arr13=np.array([1,2,3,4,5])
 arr14=np.array([6,7,8,9,10])
arr13-arr14

array([-5, -5, -5, -5, -5])

In [35]:
arr13*arr14

array([ 6, 14, 24, 36, 50])

In [36]:
arrA=np.arange(6).reshape(3,2)
arrB=np.arange(6,12).reshape(2,3)
arrA.dot(arrB)

array([[ 9, 10, 11],
       [39, 44, 49],
       [69, 78, 87]])

In [37]:
arr13

array([1, 2, 3, 4, 5])

In [38]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
arr12.sum(axis=0)#this is sum of coloums

array([40, 45, 50, 55])

In [40]:
arr12.sum(axis=1)#this is sum of rows

array([ 6, 22, 38, 54, 70])

In [41]:
arr12.transpose()#rows becomes coloums and coloums becomes rows

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [42]:
a=np.array([[11,12,13],[4,5,6]])
b=np.array([[7,8,9],[1,2,3]])
np.cross(a,b)

array([[ 4, -8,  4],
       [ 3, -6,  3]])

In [43]:
np.sort(b)#by default during sort it take axis as 1 during sort

array([[7, 8, 9],
       [1, 2, 3]])

In [44]:
np.sort(a,axis=0)

array([[ 4,  5,  6],
       [11, 12, 13]])

In [45]:
np.sort(b,kind='quicksort')#by using king argument we can select the type to sorting algorithm 

array([[7, 8, 9],
       [1, 2, 3]])

In [46]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
np.argsort(arr12)#shows the indexing of elements row-wise,axis=1 

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [49]:
np.argsort(arr12,axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]], dtype=int64)

In [50]:
np.argmin(arr12)

0

In [51]:
np.argmax(arr12)

19